name: Queszz
description: Quiz app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.2.6
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  provider: ^4.3.3
  flutter_svg: ^0.19.1
  sqflite: ^1.3.2
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/GeneralKnowledge.svg


flutter_intl:
  enabled: true

